name: CD (Deploy to Azure)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy Code Update (Image Build & Push)
        run: |
          chmod +x scripts/deploy/deploy_image_update.sh
          ./scripts/deploy/deploy_image_update.sh
